### ISSUE TITLE
INFOGRAFIA HILOS ANA KIMBERLY HERNANDEZ PEREZ

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/infografia-de-hilos-Anakimberly#2]
[INFOGRAFIA DE HILOS ANA KIMBERLY HERNANDEZ PEREZ 4BS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Anakimberly/files/15099024/INFOGRAFIA.DE.HILOS.ANA.KIMBERLY.HERNANDEZ.PEREZ.4BS.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
